### ISSUE TITLE
org.gradle.api.GradleException: androidx.navigation.safeargs exception

### ISSUE THREAD

**Issue by DBertolis** [Foxpace/SensorBox#4] opened 2021-12-13 12:07 UTC
Hi, I am hoping you can help. 

I'm trying to compile and run the SensorBox app in Android Studio. I haven't modified the code at all but I get the following error. 

"A problem occurred configuring project ':app'.
> com.android.build.gradle.internal.crash.ExternalApiUsageException: org.gradle.api.GradleException: androidx.navigation.safeargs can only be used with an androidx project"

Could you help me out? 

Thanks

**Comment by Foxpace** [comment] 2021-12-13 16:50
Hello,

this is possible duplicate of already solved issue #3 . Please try out suggested solution - adding local.properties to your project.

**Closed** 2022-04-27 21:28 UTC
